#define IDENTIFIER 0
#define CONSTANT 1
#define MAIN 2
#define IN 4
#define OUT 5
#define IF 6
#define FOR 8
#define NUMBER 10
#define BOOL 12
#define TRUE 14
#define FALSE 15
#define AND 16
#define OR 17